spring:
  application:
    name: auth-service

server:
  port: 9100

jwt:
  private-key-path: classpath:rsa/private_key.pem
  public-key-path: classpath:rsa/public_key.pem
  expiration: 86400

security:
  enable: true

secure:
  ignore-urls:
    - /auth/login      # 放行登录接口
    - /auth/register   # 放行注册接口
    - /auth/public-key