server:
  port: 9500
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

seata:
  tx-service-group: order-service-fescar-service-group

rocketmq:
  name-server: 172.31.105.105:9876

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000